### ISSUE TITLE
New animals (and other things) for the bestiary

### ISSUE THREAD

**Issue by andremaravilha** [fcampelo/EC-Bestiary#1]
#### L
- **Lion** - Maziar Yazdani and Fariborz Jolai. "Lion Optimization Algorithm (LOA): A nature-inspired metaheuristic algorithm." Journal of Computational Design and Engineering 3(1):24-36, 2016. [DOI](http://dx.doi.org/10.1016/j.jcde.2015.06.003)

#### M
- **Monkey** -  R. Zhaoand W. Tang."Monkey Algorithm for Global Numerical Optimization." Journal of Uncertain Systems 2(3):165-176,2008. [URL](http://www.worldacademicunion.com/journal/jus/jusVol02No3paper01.pdf)

#### W
- **Water Evaporation** - A. Kaveh and T. Bakhshpoori. "Water Evaporation Optimization: A novel physically inspired optimization algorithm." Computers & Structures 167:69-85, 2016. [DOI](http://dx.doi.org/10.1016/j.compstruc.2016.01.008)

**Comment by fcampelo** [comment]
Added suggestions to the bestiary. 
Thanks!
