### ISSUE TITLE
Suggestions / requests by Christian Blum

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#10]
Work on the intro text and possibly remove the year-2000 threshold, as suggested by Christian Blum via e-mail:

> "_in my opinion you should (1) work on the wording of your initial paragraphs such that everyone coming across your website understands your intentions, and (2) removing this artificial threshold of the year 2000, and simply include all works on algorithms inspired by nature (also evolutionary algorithms, ant colony optimization, etc)._"

**Comment by caranha** [comment]
Assigning myself to this issue to remind me to tackle it. I will probably have some free time to work on it this weekend.

We can probably re-add ACO and GA at once, but other "classical" works will depend on people helping us, sending issues/PRs

**Comment by fcampelo** [comment]
## Adding the classical methods 
This one should be relatively easy: 
- Chromosomes (GA)
- Metals cooling down (SA)
- Ants (ACO)
- Plus whatever it is that Evolution Strategies are based on (I can't remember if it is explicitly bio-inspired, despite the name. Gotta check.)

## Rewording the intro
This one is going to be a little more challenging - gotta find a good balance between the humor and the message. We can work together on that if you want (synchronously or not, up to you)

## Others
I've been thinking of adding a few special sections to the Bestiary: 
- maybe a FAQ would be interesting;
- maybe one with "Love letters to the editors", with the messages we receive from people who are not particularly happy with being here (fully anonymized, of course, to preserve the senders' identities)

What do you think?

**Comment by caranha** [comment]
. I think that ES actually does not use any analogies, but I might be
wrong. Agreed on the other three.

. For the intro, we might open a separate issue and write proposals as
comments until we are happy with it.

. Ambivalent about the others.

**Comment by caranha** [comment]
Ok, here is a first stab at the introduction. It merges the sections "read me first" and "Introduction". 

We can probably shorten it quite a bit, and make it more absurd -- try to make our point through subtle humour, focusing on the craziness of the huge number and variety of metaphors.

> The field of meta-heuristic search algorithms has a long tradition of finding inspiration from natural systems. Starting from the traditional "Genetic Algorithms" and "Ant Colony Optimization", in the last two decates we have observed an explosion of "nature"-inspired heuristics, such as Bird-algorithms, Cat-Algorithms and even Zombie-algorithms.

> The goal of this bestiary is to observe and catalogue the exuberance of the meta-heuristic "eco-system". We try to keep a list of the many different animals, plants, and natural and supernatural systems that can be spotted in the wild lands of bio-inspired computation literature.

> Please note that this list makes no claims about the scientific quality of the papers listed. While we personally believe that our field could do with more mathematics and less bees, the list below puts classic works of the metaheuristics literature side by side with others for which the contribution is less well-defined. Our goal is to show how many different ways are used to describe systems that deep down follow the same basic premises.

> Finally, if you know a metaphor-based method that is not listed here, or if you know of an earlier menthion of a listed method, please see the bottom of the page on how to contribute!

**Comment by fcampelo** [comment]
Great Intro! Here is my own (slightly edited) version:

The field of meta-heuristic search algorithms has a long history of finding inspiration in natural systems. Starting from classics such as _Genetic Algorithms_ and _Ant Colony Optimization_, the last two decades have witnessed a fireworks-style explosion (pun intended) of natural (and sometimes supernatural) heuristics - from Birds and Bees to Zombies and Reincarnation.

The goal of the _Evolutionary Computation Bestiary_ is to catalog the, ermm... exuberance of the meta-heuristic "eco-system". We try to keep a list of the many different animals, plants, microbes, natural phenomena and supernatural activities that can be spotted in the wild lands of the metaphor-based computation literature.

While we personally believe that the literature could do with more mathematics and less marsupials, and that we, as a community, should grow past this metaphor-rich phase in our field's history (a bit like chemistry outgrew alchemy), please note that this list makes no claims about the scientific quality of the papers listed. The _EC Bestiary_ puts classic works of the metaheuristics literature (e.g., GAs, ACO) and some that describe their methods in mostly metaphor-free language (e.g., JTF, CFO) side by side with others for which the scientific rigor is, to put it mildly, lacking. In short, it is not a _Hall of Fame_ of algorithms - think of it more as [The island of Doctor Moreau](https://en.wikipedia.org/wiki/The_Island_of_Doctor_Moreau): a place with a few good creatures, but which are vastly outnumbered by mindless beasts.

Finally, if you know a metaphor-based method that is not listed here, or if you know of an earlier mention of a listed method, please see the bottom of the page on how to contribute!

**Comment by fcampelo** [comment]
Regarding the open issue of "Adding the classical methods", here's an updated checklist for ourselves:

- [] Chromosomes (GA)
- [] Metals cooling down (SA)
- [] Ants (ACO)
- [] Animal swarms (PSO)

**Comment by caranha** [comment]
Added the introduction to the main page (no comments from my part).

**Comment by caranha** [comment]
Added ACO and SA. PSO is a bit too abstract for me to really consider it a metaphor -- re-reading the paper, it has closer roots to artificial life systems than actually any natural metaphor.

I am not sure which of holland's papers would be the best reference for GA... will leave this open for now.

**Comment by fcampelo** [comment]
On the topic of GA: what about skipping the papers and settling it by referencing Holland's book "Adaptation in Natural and Artificial Systems" (1975)? It seems to be the most widely used source as the "original" work on GAs.

**Comment by caranha** [comment]
Holy necro, batman. I think that is a grand idea, anyway.
