### ISSUE TITLE
Another black widow algorithm

### ISSUE THREAD

**Issue by albertofranzin** [fcampelo/EC-Bestiary#101]
https://www.sciencedirect.com/science/article/abs/pii/S0957417420309003

Essam H. Houssein, Bahaa El-din Helmy, Diego Oliva, Ahmed A. Elngar, Hassan Shaban,
"A novel Black Widow Optimization algorithm for multilevel thresholding image segmentation", Expert Systems with Applications, 2020.

**Comment by caranha** [comment]
Two black widows in the same year? Are these competing laboratories or something? :-P
