### ISSUE TITLE
Arithmetic Optimization Algorithm

### ISSUE THREAD

**Issue by albertofranzin** [fcampelo/EC-Bestiary#103]
Laith Abualigah, Ali Diabat, Seyedali Mirjalili, Mohamed Abd Elaziz, Amir H. Gandomi, The Arithmetic Optimization Algorithm, Computer Methods in Applied Mechanics and Engineering, Volume 376, 2021.

https://www.sciencedirect.com/science/article/pii/S0045782520307945

https://www.researchgate.net/publication/348433063_The_Arithmetic_Optimization_Algorithm

**Comment by caranha** [comment]
Silly paper, but not really a metaphor :-)
