### ISSUE TITLE
More animals

### ISSUE THREAD

**Issue by albertofranzin** [fcampelo/EC-Bestiary#104]
Orcas

Drias H., Drias Y., Khennak I. (2020) A New Swarm Algorithm Based on Orcas Intelligence for Solving Maze Problems. In: Rocha Á., Adeli H., Reis L., Costanzo S., Orovic I., Moreira F. (eds) Trends and Innovations in Information Systems and Technologies. WorldCIST 2020. Advances in Intelligent Systems and Computing, vol 1159. Springer, Cham. https://doi.org/10.1007/978-3-030-45688-7_77

https://link.springer.com/chapter/10.1007%2F978-3-030-45688-7_77

Border Collie

T. Dutta, S. Bhattacharyya, S. Dey and J. Platos, "Border Collie Optimization," in IEEE Access, vol. 8, pp. 109177-109197, 2020, doi: 10.1109/ACCESS.2020.2999540.

https://ieeexplore.ieee.org/document/9106341/

**Comment by fcampelo** [comment]
Spotted by Marco Pranzo, Università di Siena:

A shuffled multi-swarm micro-migrating birds optimizer...
deserves a try! ;)

<https://www.sciencedirect.com/science/article/pii/S002002551630617X>

**Comment by albertofranzin** [comment]
I think horses are still missing.

https://link.springer.com/chapter/10.1007%2F978-3-030-51971-1_16

Moldovan D. (2020) Horse Optimization Algorithm: A Novel Bio-Inspired Algorithm for Solving Global Optimization Problems. In: Silhavy R. (eds) Artificial Intelligence and Bioinspired Computational Methods. CSOC 2020. Advances in Intelligent Systems and Computing, vol 1225. Springer, Cham. https://doi.org/10.1007/978-3-030-51971-1_16

**Comment by caranha** [comment]
Horses!
