### ISSUE TITLE
Pidgeon-Inspired optimization

### ISSUE THREAD

**Issue by pedrocastellucci** [fcampelo/EC-Bestiary#107]
I hope you are doing fine. 

I have come across this paper: https://link.springer.com/article/10.1007/s10489-021-02302-9 which mentions  pigeon-inspired optimization. 

I tracked the original reference to: https://www.emerald.com/insight/content/doi/10.1108/IJICC-02-2014-0005/full/html. 

The full reference is: 
- Duan, Haibin, and Peixin Qiao. "Pigeon-inspired optimization: a new swarm intelligence optimizer for air robot path planning." International journal of intelligent computing and cybernetics (2014).

**Comment by caranha** [comment]
Thank you Pedro! We actually already have that one :-D
