### ISSUE TITLE
Add contribution by TJRS

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#13]
- [x] Check for eligibility
- [x] Check for duplicates
- [x] Add to bestiary

[http://www.inderscience.com/offer.php?id=81473](http://www.inderscience.com/offer.php?id=81473)
Sperm motility algorithm: a novel metaheuristic approach for global optimisation
by Osama Abdel Raouf; Ibrahim M. Hezam
International Journal of Operational Research (IJOR), Vol. 28, No. 2, 2017

**Comment by caranha** [comment]
Holy fecundity, batman! Added.
