### ISSUE TITLE
New suggestions by Marc Sevaux

### ISSUE THREAD

**Issue by caranha** [fcampelo/EC-Bestiary#14]
- [ ] Check for Eligibility
- [ ] Check for Duplicates
- [ ] Add to Bestiary

Teaching–learning-based optimization
http://dx.doi.org/10.1016/j.cad.2010.12.015

Crisscross optimization algorithm
http://dx.doi.org/10.1016/j.knosys.2014.05.004

Binary Bat Algorithm
http://link.springer.com/article/10.1007%2Fs00521-013-1525-5
http://dx.doi.org/10.1007/s00521-013-1525-5

**Comment by caranha** [comment]
I don't think that the Crisscross actually counts as a heuristic, even though the paper has some weird motivations in its introduction. Opinions?

**Comment by caranha** [comment]
Sorry to be a party-popper, but you should read the introduction. The basis
of the "crisscross" is that the arrange the algorithms in a matrix, and do
a column based crossover followed by a row based crossover. The idea is a
bit (a lot?) of a non-sequitur, but I think there is no metaphor here. The
best allegory I could make is if someone proposed a "prime-number mutation"
where only the solutions with indexes that are prime undergo mutation.

As for the confucious comment, it is weird, and comes out of left field,
but it is never mentioned again besides the first paragraph of the intro
(along with the gold ratio). They never explain exactly what it is exactly
that is inspired by confucius in their algorithm.

"If everything is a metaphor, then nothing is a metaphor" :-P

(PS: my previous comments said "counts as a heuristic", obviously, I meant
"count as a metaphor")

**Comment by fcampelo** [comment]
Holy confusing Confucius, Batman!!!
Sure enough, no obvious metaphor here. Just another poorly-worded abstract.

**Comment by caranha** [comment]
Still need to add the other two methods, so I'm leaving this open for now

**Comment by caranha** [comment]
Teacher and Bat algorithms are duplicates. Closing this.
