### ISSUE TITLE
Break down the bestiary into multiple files

### ISSUE THREAD

**Issue by caranha** [fcampelo/EC-Bestiary#20]
It is getting a bit unwieldly to edit the huge readme. 

Ideally we would be able to create a bib file for the bestiary, a header and footer file, and use some sort of script to knit together the whole thing as a markdown file.

**Comment by fcampelo** [comment]
Hi Claus!

Great work on cleaning up our Issue backlog!!! Thanks!

I've been thinking the same thing for a while - having either a .bib or a simple .csv file with the paper data, and a routine to assemble the page. Using a CSV would even allow us to easily calculate some statistics (on journals, authors, etc.), but using BIB would also have some advantages.

Writing the script shouldn't take too long (I figure I can get a first working draft in hour or so of coding), but migrating the data on all existing papers to the new format would probably  I'll work on it as soon as my desk clears a bit - gotta finish our paper first ;-)

**Comment by fcampelo** [comment]
Done (see v2-devel branch)
