### ISSUE TITLE
New suggestion by Kenneth

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#21]
Plant intelligence...

http://download.springer.com/static/pdf/600/art%253A10.1007%252Fs10462-016-9486-6.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Farticle%2F10.1007%2Fs10462-016-9486-6&token2=exp=1489677113~acl=%2Fstatic%2Fpdf%2F600%2Fart%25253A10.1007%25252Fs10462-016-9486-6.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Farticle%252F10.1007%252Fs10462-016-9486-6*~hmac=e5671e7ee2e3b79d37ca289c3677f09fc8836953a353f3ec15172d3e397431ec

**Comment by caranha** [comment]
Added
