### ISSUE TITLE
Check suggestions by Sara Silva

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#22]
Kaizen Japanese methodology:
http://dl.acm.org/citation.cfm?id=2598264

Sand piles:
https://books.google.pt/books?id=GDz2nCAJpJ4C&pg=PA378&lpg=PA378&dq=sand+pile+mutation&source=bl&ots=3V0C2kbO6Y&sig=GNGWFlJum1u4ingo3Fd9jA_uy2M&hl=en&sa=X&ved=0ahUKEwjQwJSXgMbTAhUFOxQKHeqkDC0Q6AEISzAK#v=onepage&q=sand%20pile%20mutation&f=false

Algae:
S.A. Uymaz, G. Tezel, E.Yel, Artificial Algae Algorithm (AAA) For Nonlinear Global Optimization, Applied Soft Computing, Volume 31, June 2015, Pages 153-171.

**Comment by caranha** [comment]
Done! (Could not access Sand Pile, though)

**Comment by fcampelo** [comment]
The sand piles one does not fulfill the inclusion criteria 2:

> 2. the title or abstract must name the algorithm after the natural (or supernatural) metaphor on which it was based;
