### ISSUE TITLE
Algorithms to include

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#26]
- [x] Thermal exchange optimization: http://www.sciencedirect.com/science/article/pii/S0965997817300066
- [x] Vibrating particles system: http://doi.org/10.1007/s00707-016-1725-z
- [x] Tug-of-war: A. Kaveh, A. Zolghadr "A novel meta-heuristic algorithm: tug of war optimization" - Asian J Civil Eng, 6 (4) (2016), pp. 469–492

**Comment by fcampelo** [comment]
- [ ] Infectious Diseases: Artificial infectious disease optimization: A SEIQR epidemic dynamic model-based function optimization algorithm

**Comment by caranha** [comment]
Do we need to add any contributor for these papers?

**Comment by fcampelo** [comment]
"Infectious diseases" was spotted by Iago A. de Carvalho. The others are from my personal trophy collection ;-)

I'll add Iago to the list of contributors.

Cheers,
