### ISSUE TITLE
More Algorithms to add

### ISSUE THREAD

**Issue by caranha** [fcampelo/EC-Bestiary#29]
“Research on Permutation Flow-shop Scheduling Problem based on Improved Genetic Immune Algorithm with vaccinated offspring” [[link](https://doi.org/10.1016/j.procs.2017.08.055>)]

By Federico Pagnozzi from ulb.ac.be

**Added by Felipe on 2018-03-31**

**Comment by fcampelo** [comment]
1) M. Ghaemi and M.-R. Feizi-Derakhshi. "Forest Optimization Algorithm." Expert Systems with Applications 41:6676-6687. DOI: 10.1016/j.eswa.2014.05.009.
2) H. Moez, A. Kaveh and N. Taghizadieh. "Natural Forest Regeneration Algorithm: A new Meta-Heuristic." Iranian Journal of Science and Technology, Transactions of Civil Engineering 40:311-326. DOI: 10.1007/s40996-016-0042-z.

By Jakub Grabski from Poznan University of Technology, Poland

**Comment by fcampelo** [comment]
Bird Swarm Algorithm: http://www.tandfonline.com/doi/abs/10.1080/0952813X.2015.1042530

**Comment by fcampelo** [comment]
Volleyball leagues: https://www.sciencedirect.com/science/article/pii/S1568494617307068
Pearl hunting: https://link.springer.com/chapter/10.1007/978-3-642-34413-8_26

By Kenneth Sörensen

**Comment by fcampelo** [comment]
All candidates reviewed/added.
