### ISSUE TITLE
Algorithms to Add, February 2018 Edition

### ISSUE THREAD

**Issue by caranha** [fcampelo/EC-Bestiary#30]
Suggested by Joaquin Antonio Pacheco, from ubu.es

- [x] Grasshopper Optimisation
Shahrzad Saremi,  Seyedali Mirjalili, and Andrew Lewis "Grasshopper Optimisation Algorithm: Theory and application" Advances in Engineering Software, Volume 105, March 2017, Pages 30-47

- [x] Sin-Cosine
Seyedali Mirjalili "SCA: A Sine Cosine Algorithm for solving optimization problems"
Knowledge-Based Systems, Volume 96, 15 March 2016, Pages 120-133

Tasks:
- [  ] Check the above papers for duplicates in the bestiary
- [  ] Check for the eligibility criteria (Metaphor, In Press)
- [  ] Add to the bestiary

**Checked on 2018-03-31 by Felipe. Not added (Grasshopper already in, Sine-Cosine not a metaphor (dubious science, but not metaphorically so)**

**Comment by caranha** [comment]
Suggested by ruben Ruiz

"Red Deer Algorithm (RDA); A New Optimization Algorithm Inspired by Red
Deers' Mating

https://scholar.google.com/scholar?cluster=18109071724224247463&hl=en&as_sdt=0,5&sciodt=0,5
​
"Abstract- In this paper, a new optimization algorithm inspired by Red Deers’ mating is developed. The Scottish Red Deer (Cervus Elaphus Scoticus) is a subspecies of Red Deer, which is native to the British Isles. We study the unusual mating behavior of Red Deers, in order to employ this behavior in designing an optimization algorithm. Red Deer Algorithm (RDA) starts with an initial population. Population individuals called Red Deers are divided in two types: hinds and male Red Deers that all together forms some harems. A harem is a group of females, which mate with the head of harem. The competition of male Red Deers to get the harem with more hinds, is the basis of the proposed evolutionary algorithm. During this match, which just male Red Deers will win this competition with their abilities such as: roaring and fighting. They will take a concession mating with a percentage of hinds. It can generate other solutions and select the best solution and will be competitive with other male Red Deers. Applying the purposed RDA to some of benchmark function, shows its ability in dealing with different types of optimization problem."



"SOCIAL ENGINEERING OPTIMIZATION (SEO), A NEW SINGLE-SOLUTION
META-HEURISTIC INSPIRED BY SOCIAL ENGINEERING"

http://www.sid.ir/En/Seminar/ViewPaper.aspx?ID=34338
http://www.sid.ir/FileServer/SE/502e20171319

**Comment by albertofranzin** [comment]
More viruses:

Morteza Jaderyan, Hassan Khotanlou, "Virulence Optimization Algorithm", Applied Soft Computing, vol. 43, 2016
https://www.sciencedirect.com/science/article/pii/S1568494616300898

Mu Dong Li, Hui Zhao, Xing Wei Weng, Tong Han "A novel nature-inspired algorithm for optimization: Virus colony search", Advances in Engineering Software, vol. 92, 2016
https://www.sciencedirect.com/science/article/pii/S0965997815001702

**Comment by albertofranzin** [comment]
Najmeh Sadat Jaddi, Jafar Alvankarian, Salwani Abdullah,  "Kidney-inspired algorithm for optimization problems", Communications in Nonlinear Science and Numerical Simulation, vol. 42, 2017
https://www.sciencedirect.com/science/article/pii/S1007570416302039

**Comment by albertofranzin** [comment]
Qingyang Zhang, Ronggui Wang, Juan Yang, Kai Ding, Yongfu Li, Jiangen Hu "Collective decision optimization algorithm: A new heuristic optimization method", Neurocomputing, vol. 221, 2017
https://www.sciencedirect.com/science/article/pii/S0925231216311183

**Comment by albertofranzin** [comment]
Varun Punnathanam, Prakash Kotecha "Yin-Yang-pair Optimization: A novel lightweight optimization algorithm", Engineering Applications of Artificial Intelligence, vol. 54, 2016
https://www.sciencedirect.com/science/article/pii/S0952197616300811

(so finally one starting with Y)

**Comment by fcampelo** [comment]
Contribution spotted in the wild by Thomas Stützle:
https://link.springer.com/article/10.1007%2Fs11432-012-4548-0

"Lion pride optimizer: An optimization algorithm inspired by lion pride behavior” published in the journal

Science China Information Sciences

October 2012, Volume 55, Issue 10, pp 2369–2389.

**Comment by borisalmonacid** [comment]
Title: "**Andean Condor Algorithm for cell formation problems**"
Authors: Boris Almonacid, Ricardo Soto
Source: https://link.springer.com/article/10.1007%2Fs11047-018-9675-0
First Online: 01 March 2018


Abstract
"This paper proposes a novel population-based optimization algorithm called Andean Condor Algorithm (ACA) for solving cell formation problems. The ACA metaheuristic is inspired by the movement pattern of the Andean Condor when it searches for food. This pattern of movement corresponds to the flight distance traveled by the Andean Condor from its nest to the place where food is found. This distance varies depending on the seasons of the year. The ACA metaheuristic presents a balance of its population through a performance indicator based on the average quality of the population’s fitness. This balance determines the number of Andean Condors that will perform an exploration or intensification movements. ACA metaheuristics have a flexible design. It allows to easily integrate specific heuristics according to the optimization problem to be solved. Two types of computational experiments have been performed. According to the results obtained it has been possible to determine that ACA is an algorithm with an outstanding RPD% in relation to the algorithms BAT, MBO and PSO, robust and with a convergence which tends not to be trapped in the local optimums. Besides, according to the non-parametric multiple comparisons, results have been obtained in which the ACA metaheuristic has significant differences in relation to the BAT, MBO and PSO algorithms."

**Comment by iagoac** [comment]
Metaheuristic name: "Squirrel Search Algorithm"
Paper Title: "A novel nature-inspired algorithm for optimization: Squirrel search algorithm"
Authors: Mohit Jain, Vijander Singh, and Asha Rani
Source: https://www.sciencedirect.com/science/article/pii/S2210650217305229
First Online: February 28, 2018

Abstract
"This paper presents a novel nature-inspired optimization paradigm, named as squirrel search algorithm (SSA). This optimizer imitates the dynamic foraging behaviour of southern flying squirrels and their efficient way of locomotion known as gliding. Gliding is an effective mechanism used by small mammals for travelling long distances. The present work mathematically models this behaviour to realize the process of optimization. The efficiency of the proposed SSA is evaluated using statistical analysis, convergence rate analysis, Wilcoxon's test and ANOVA on classical as well as modern CEC 2014 benchmark functions. An extensive comparative study is carried out to exhibit the effectiveness of SSA over other well-known optimizers in terms of optimization accuracy and convergence rate. The proposed algorithm is implemented on a real-time Heat Flow Experiment to check its applicability and robustness. The results demonstrate that SSA provides more accurate solutions with high convergence rate as compared to other existing optimizers.."

**Comment by fcampelo** [comment]
All candidates checked/added.
