### ISSUE TITLE
Algorithms to include

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#34]
Contributed by Iago Augusto (UFMG, Brazil):

> N.Ath. Kallioras, N.D. Lagaros, D.N. Avtzis, “Pity Beetle Algorithm - A new metaheuristic inspired by the behaviour of bark beetles”, Advances in Engineering Software, Volume 121, July 2018, Pages 147-166, 2018
> 
> In the past years a great variety of nature-inspired algorithms have proven their ability to efficiently handle combinatorial optimization problems ranging from design and form finding problems to mainstream economic theory and medical diagnosis. In this study, a new metaheuristic algorithm called Pity Beetle Algorithm (PBA) is presented and its efficiency against state-of-the-art algorithms is assessed. The proposed algorithm was inspired by the aggregation behavior, searching for nest and food, of the beetle named Pityogenes chalcographus, also known as six-toothed spruce bark beetle. This beetle has the ability to locate and harvest on the bark of weakened trees into a forest, while when its population exceeds a specific threshold it can infest healthy and robust trees as well. As it was proved in this study, PBA can be applied to NP-hard optimization problems regardless of the scale, since PBA has the ability to search for possible solutions into large spaces and to find the global optimum solution overcoming local optima. In this work, PBA was applied to well-known benchmark uni-modal and multi-modal, separable and non-separable unconstrained test functions while it was also compared to other well established metaheuristic algorithms implementing also the CEC 2014 benchmark and complexity evaluation tests.
> 
> https://www.sciencedirect.com/science/article/pii/S0965997817305239

**Comment by fcampelo** [comment]
Spotted in the wild:

- Crows (_A novel metaheuristic method for solving constrained engineering optimization problems: crow search algorithm_)
- Duelists (_Duelist Algorithm: An Algorithm Inspired by How Duelist Improve Their Capabilities in a Duel_)
- Ecogeography (_Ecogeography-based optimization: enhancing biogeography-based
optimization with ecogeographic barriers and differentiations_)
- Neuronal Communication (_New Meta-heuristic Optimization Algorithm Using Neuronal Communication_)
- Spotted Hyenas (_Spotted hyena optimizer: A novel bio-inspired based metaheuristic technique for engineering applications._)
- Swine Flu (_Swine influenza models based optimization (SIMBO)_)
- Hydrological Cycles (_Hydrological Cycle Algorithm for Continuous Optimization Problems_)
- Rain water (_Optimization of Energy Efficiency and Conservation in Green Building Design Using Duelist, Killer-Whale and Rain-Water Algorithms_)
- Rainfall (_Rain-fall optimization algorithm: A population based algorithm for solving constrained optimization problems_)
- Sonar (_A New Metaheuristic Method for Optimization: Sonar Inspired Optimization_)
- Vision Correction (_KU battle of metaheuristic optimization algorithms 1: Development of six new/improved algorithms_)
- Passing Vehicles (_Passing vehicle search (PVS): A novel metaheuristic algorithm_)

**Comment by caranha** [comment]
By the power of procastination, I have added most of the algorithms above. Notable exceptions: 
- Rain Water: I considered to be the same category as rainfall
- Vision Correction: I took a look at the paper that generated this algorithm, and just couldn't do it. Nope. No. Sorry, this broke my mental sanity.

**Comment by fcampelo** [comment]
Holy procrastination, Batman! Good job! :-)

**Comment by caranha** [comment]
Finding the DOI, copying it into DOI2BIB, and then copying it to the correct cage makes things easy :-)
