### ISSUE TITLE
Add the famous ones

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#4]
- Immune systems (AIS)
- Chromosomes (GA)
- Metals cooling down (SA)

**Comment by caranha** [comment]
And Neurons

**Comment by fcampelo** [comment]
You mean Neural Nets? I don't think they qualify here (they're not considered a metaheuristic, are they?)

**Comment by caranha** [comment]
You are right, I just thought about the "metaphor" part of the scope, not the metaheuristics.

**Comment by fcampelo** [comment]
Added an early reference to AIS (CLONAL). Not sure how to include the other two. Suggestions are welcome.
