### ISSUE TITLE
may you add the same for code packages not only papers

### ISSUE THREAD

**Issue by Sandy4321** [fcampelo/EC-Bestiary#41]
it would be great to have similar for code

**Comment by fcampelo** [comment]
What do you mean?

**Comment by Sandy4321** [comment]
thanks for soon answer
it would be great  to create a collection of implemented in code algorithms (references /links to packages for mentioned in papers algorithms  )

you did the collection of  only papers

**Comment by fcampelo** [comment]
Hi @Sandy4321,

Thank you for the suggestion, but this is not the objective of the Bestiary - our goal is to point out the absurdity of basing algorithm development on metaphors, not to curate a collection of implementations of all these weird methods. 

Cheers!
Felipe
