### ISSUE TITLE
Meerkats and Cheetahs and Coyotes, oh my!

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#42]
Two by the very same author, in the very same event!

KLEIN, CARLOS E. ; COELHO, L. S. . Meerkats-inspired algorithms for global optimization problems. In: European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN), 2018, Bruges. European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN). Louvain-la-Neuve: Ciaco, Michel Verleysen (editor), 2018. v. 1. p. 679-684.

KLEIN, CARLOS E. ; MARIANI, V. C. ; COELHO, L. S. . Cheetah based optimization algorithm: a novel swarm intelligence paradigm. In: European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN), 2018, Bruges. European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN). Louvain-la-Neuve: Ciaco, Michel Verleysen, 2018. v. 1. p. 685-690.

Also to check/include:

PIEREZAN, J. ; COELHO, LEANDRO DOS S. . Coyote Optimization algorithm: a new metaheuristic for global optimization problems. In: EEE Congress on Evolutionary Computation (IEEE CEC), 2018, Rio de Janeiro. EEE Congress on Evolutionary Computation (IEEE CEC). Piscataway,NJ: IEEE Press, 2018. v. 1. p. 1-6. 

Gai-Ge Wang ; GAO, X. ; ZENGER, K. ; COELHO, L. S. . A novel metaheuristic algorithm inspired by rhino herd behavior. In: 9th Eurosim Congress on Modelling and Simulation (EUROSIM 2016), 2016, Oulu. 9th Eurosim Congress on Modelling and Simulation (EUROSIM 2016), 2016. v. 1. p. 1-6.

**Comment by caranha** [comment]
Added all these badboys. The ESANN papers were a bit annoying because the doi was not available and google scholar did not have the correct TEX. Also, the Rhino paper had the wrong year on google scholar (replaces our current, later rhino paper).

Coelho's paper title are quite formulaic, huh? "X-inspired algorithm: a Novel Global Optimization Paradigm" :-1:

**Comment by fcampelo** [comment]
"Paradigm" is one of these words that had a great epistemological meaning, but then got hijacked and ended up being essentially and empty term. 👎
