### ISSUE TITLE
Butterfly Optimization

### ISSUE THREAD

**Issue by caranha** [fcampelo/EC-Bestiary#43]
> I came across another metaphor based method "butterfly optimization
> algorithm" which I think can be added to the list. I am aware that "Monarch
> butterfly optimization" is also in the list and inspired from butterfly
> behaviour, however, these are different algorithms (Like different 'novel'
> fish algorithms. Rest it's up to you. I just want to let you know.
> 
> Link to Butterfly Optimization Algorithm can be found here (
> https://link.springer.com/article/10.1007/s00500-018-3102-4)
> 

Dr. Rahul Roy

**Comment by fcampelo** [comment]
@caranha , what's the affiliation of Dr. Roy? (so that we can add him to our list of contributors)

**Comment by caranha** [comment]
He did not respond to my question about adding to the bestiary, so I'm not sure :-/
