### ISSUE TITLE
New beasts to cage

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#45]
Spotted in the wild by Rafael Stubs Parpinelli (UDESC, Brazil)

- [x] Gai-Ge Wang, Suash Deb, Leandro dos Santos Coelho:
Earthworm optimisation algorithm: a bio-inspired metaheuristic algorithm for global optimisation problems. IJBIC 12(1): 1-22 (2018)

- [x] Juliano Pierezan, Leandro dos Santos Coelho:
Coyote Optimization Algorithm: A New Metaheuristic for Global Optimization Problems. CEC 2018: 1-8.

**Comment by iagoac** [comment]
- Artificial Feeding Birds (AFB): A New Metaheuristic Inspired by the Behavior of Pigeons
https://link.springer.com/chapter/10.1007%2F978-3-319-96451-5_3

Finally, the pigeons have their algorithm!

**Comment by caranha** [comment]
These algorithms are starting to blend together, I am pretty sure I saw the "Golden Sine" and the "Earthworm" before O.o

**Comment by albertofranzin** [comment]
- Queuing search algorithm: A novel metaheuristic algorithm for solving engineering optimization problems https://www.sciencedirect.com/science/article/pii/S0307904X18302890

Filed under: human behavior? In the list there is already an older algorithm inspired by Social Behavior.

**Comment by caranha** [comment]
Added all these bad boys! (Queuing under Social Behavior)

@iagoac Actually, there was another (self-)suggestion of pigeons from 2016, and when checking I found the earliest pigeon to be from 2014!

Pigeons are everywhere! :-)
