### ISSUE TITLE
Camels has incorrect doi

### ISSUE THREAD

**Issue by evdcush** [fcampelo/EC-Bestiary#49]
The Camels entry, in the [C cage](https://github.com/fcampelo/EC-Bestiary/blob/master/Cages/C.bib), is attributed an incorrect doi. 

That publication does not have a doi, but the one provided (10.1007/s00707-009-0270-4) points to the [charged systems](https://doi.org/10.1007/s00707-009-0270-4) paper.

Here is the corrected bibtex:

```
@article{Camels,
  year  = {2016},
  volume = {12},
  number = {2},
  pages = {167--177},
  issn = {18145892},
  author = {M. K. Ibrahim, R. S. Ali},
  title = {Novel Optimization Algorithm Inspired by Camel Traveling Behavior},
  journal = {Iraq J. Electrical and Electronic Engineering},
}
```

This url points to the article, which also has a full-text link: 
`url = {https://www.iasj.net/iasj?func=article&aId=118375}`

**Comment by fcampelo** [comment]
Thanks @evdcush , will fix it when I perform this month's maintenance in the bestiary.

Cheers!
