### ISSUE TITLE
Suggestions by Christian L. Camacho Villalón (ULB, Brussels)

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#50]
- [x] Human seekers: https://doi.org/10.1109/TIE.2009.2031194
- [x] Particle collisions: "A New Stochastic Optimization Algorithm based on a Particle Collision Metaheuristic"
- [x] Molecular dynamics: https://doi.org/10.1016/j.knosys.2018.08.030
- [x] Selfish herds (!): http://dx.doi.org/10.1016/j.biosystems.2017.07.010
- [x] Mouth Brooding Fish: https://doi.org/10.1016/j.asoc.2017.09.035
- [x] Saplings Growing Up: "Thinking Capability of Saplings Growing Up Algorithm"
- [x] Bees Collecting Pollen: "A Novel Global Convergence Algorithm: Bee Collecting Pollen Algorithm"
- [x] Yellow Saddle Goldfish: https://doi.org/10.1016/j.biosystems.2018.09.007
- [x] Galatic Swarms: http://dx.doi.org/10.1016/j.asoc.2015.10.034

**Comment by caranha** [comment]
Human Seekers -> Social Behavior: Seeking
Particle Collision -> Nuclear Collision
Sampling Growing up -> Plants: Sampling Growth
Bees collecting Polen -> Collision with bee colony, not added
