### ISSUE TITLE
Paper Suggestion

### ISSUE THREAD

**Issue by caranha** [fcampelo/EC-Bestiary#51]
> Maybe this is of any interest:
> 
> https://ieeexplore.ieee.org/document/7482120
> 
> Kind regards
> Tony Wauters

**Comment by albertofranzin** [comment]
One more about crows: Crow Swarm Optimization

http://www.jardcs.org/backissues/abstract.php?archiveid=6598
https://www.researchgate.net/publication/331523882_A_Novel_Metaheuristic_Algorithm_for_Multiple_Traveling_Salesman_Problems

**Comment by caranha** [comment]
- Football optimization --> not added, older soccer paper already included.
- Crow optimization --> not added, older crow paper already exists.
