### ISSUE TITLE
new approaches related to evolutionary and swarm approaches

### ISSUE THREAD

**Issue by lscoelho** [fcampelo/EC-Bestiary#53]

**Comment by lscoelho** [comment]
A new meta-heuristic optimizer: Pathfinder algorithm
Applied Soft Computing, Volume 78, May 2019, Pages 545-568
Hamza Yapici, Nurettin Cetinkaya

Emperor penguin optimizer: A bio-inspired algorithm for engineering problems
Knowledge-Based Systems, Volume 159, 1 November 2018, Pages 20-50
Gaurav Dhiman, Vijay Kumar

Design of heat exchangers using falcon optimization algorithm
Applied Thermal Engineering, Volume 156, 25 June 2019, Pages 119-144
Emerson Hochsteiner de Vasconcelos Segundo, Viviana Cocco Mariani, Leandro dos Santos Coelho

Seagull optimization algorithm: Theory and its applications for large-scale industrial engineering problems
Knowledge-Based Systems, Volume 165, 1 February 2019, Pages 169-196
Gaurav Dhiman, Vijay Kumar

**Comment by caranha** [comment]
Thank you! will take a look!

**Comment by caranha** [comment]
- Pathfinder algorithm -- can't quite figure out where to put the metaphor -- is this even a metaphor? "Led swarms?!"
- Emperor Penguin -- Added!
- Falcons -- Added!
- Seagull -- Added!
