### ISSUE TITLE
Sandpiper optimization algorithm

### ISSUE THREAD

**Issue by iagoac** [fcampelo/EC-Bestiary#55]
**Sandpiper optimization algorithm: a novel approach for solving real-life engineering problems**
It was published last week on Applied Intelligence

[https://link.springer.com/article/10.1007%2Fs10489-019-01507-3](https://link.springer.com/article/10.1007%2Fs10489-019-01507-3)

Have a look at how this new algorithm works: [http://gph.is/28XaA7F](http://gph.is/28XaA7F)

**Comment by thieunguyen5991** [comment]
Have you guys check it or not? I have check this paper and have some comments in this forum. 
https://www.researchgate.net/publication/334897831_Sandpiper_optimization_algorithm_a_novel_approach_for_solving_real-life_engineering_problems
As I see, this is totally trash algorithm and trash paper. This is one of the most reason why so many researchers call meta-heuristics as the name of bullshit and unethical. 
https://www.researchgate.net/post/Metaheuristics_and_the_Emperors_new_clothes-why_do_I_care_and_worry
https://www.researchgate.net/post/Metaheuristics_for_the_simplest_combinatorial_problems-why

**Comment by fcampelo** [comment]
Copying my own answer to your similar comments in another issue:

Hi Thieu,

The vast majority of the "beasts" we catalogue are BS. That's the main reason why we started this little collection, to poke fun at the exuberant madness of the field. ;-) We think we make it pretty clear in the Introduction, e.g.:

 > In short, it is not a Hall of Fame of algorithms - think of it more as The island of Doctor Moreau: a place with a few good creatures, but which are vastly outnumbered by mindless beasts.

(Believe it or not, some authors seem to miss this point completely, and voluntarily ask for their personal inventions to be added!)

Anyway, thanks for pointing the absurdity of these particular methods. ;-)

Cheers,
Felipe

**Comment by thieunguyen5991** [comment]
Dear Felipe,

Thank you for clearing my misunderstanding.

This repository is really famous and well-known by many researchers. Some people use it to know which algorithm already exist, while others use it to learn and use the algorithm they like. Especially for newbie come to this community, they will not know which algorithm is good and worst, as you say, most of them are bullshit.

So why not use a small checkmark before the algorithms have proven their effectiveness, (and a link of proof code). This will not only help readers see which algorithm is good, but it will also help them avoid wasting time exploring the bullshit algorithm to solve their problems. It's just a simple idea but I will help a lot of researchers save their time.

I have just started learning metaheuristics for 10 months. So I have a small list of worked-algorithm and list of faked-algorithm, with proof code and explanation. Like I said before, If you have time, take a look at it. (https://github.com/thieunguyen5991/metaheuristics)

Best regards,
Thieu

**Comment by caranha** [comment]
Hello Thieu,

I'm Claus, I am the other original author of the bestiary together with Felipe.

Thank you so much for your comments. I am a bit surprised that you say that many researchers use this work as a reference. The goal of me and Felipe from the start was to make something a bit more "comical", if you understand what I mean. Maybe we should re-write the introduction again to make sure that the readers will know that this is not a "scholarly curated list". But I think that there will always be people that misunderstand.

I understand your desire to have a "checklist" of where the algorithms presented here are implemented with open source and tested with some standard problems. Me and Felipe have discussed this idea many years ago, but we decided that unfortunately it would be too big of a task for just the two of us.

If you and your colleagues are interested in creating example implementations of some of these methods, and testing and judging them, I would be happy to check your work and possibly list your implementations/tests as a sister site for the bestiary!

But maybe that would be a different Github Issue ;-)

**Comment by caranha** [comment]
Closed the issue, but added the "discussion" label so we can refer back to it in the future.
