### ISSUE TITLE
Emperor Penguin Optimizer

### ISSUE THREAD

**Issue by iagoac** [fcampelo/EC-Bestiary#56]
**Emperor penguin optimizer: A bio-inspired algorithm for engineering problems**
This is a variation of the Penguins Search Optimization Algorithm (I think).

[https://www.sciencedirect.com/science/article/pii/S095070511830296X](https://www.sciencedirect.com/science/article/pii/S095070511830296X)

Sadly, I was unable to find a gif for this one.

**Comment by caranha** [comment]
Ah, someone already suggested this one a few months ago, but thanks for the issue!
