### ISSUE TITLE
Sooty Tern Optimization Algorithm

### ISSUE THREAD

**Issue by iagoac** [fcampelo/EC-Bestiary#57]
**STOA: A bio-inspired based optimization algorithm for industrial engineering problems**

[https://www.sciencedirect.com/science/article/pii/S0952197619300715](https://www.sciencedirect.com/science/article/pii/S0952197619300715)

**Comment by thieunguyen5991** [comment]
Have you guys check it or not? I have check this paper and have some comments in this forum.
https://www.researchgate.net/publication/333537679_STOA_A_bio-inspired_based_optimization_algorithm_for_industrial_engineering_problems
As I see, this is totally trash algorithm and trash paper. This is one of the most reason why so many researchers call meta-heuristics as the name of bullshit and unethical.
https://www.researchgate.net/post/Metaheuristics_and_the_Emperors_new_clothes-why_do_I_care_and_worry
https://www.researchgate.net/post/Metaheuristics_for_the_simplest_combinatorial_problems-why

**Comment by fcampelo** [comment]
Hi Thieu,

The vast majority of the "beasts" we catalogue are BS. That's the main reason why we started this little collection, to poke fun at the exuberant madness of the field. ;-) 

(Believe it or not, some authors seem to miss this point completely, and voluntarily ask for their personal inventions to be added!)

Anyway, thanks for pointing the absurdity of these particular methods. ;-)

Cheers,
Felipe
