### ISSUE TITLE
The "algorithm of the innovative gunner" (AIG)

### ISSUE THREAD

**Issue by albertofranzin** [fcampelo/EC-Bestiary#59]
Paweł Pijarski & Piotr Kacejko (2019) A new metaheuristic optimization method: the algorithm of the innovative gunner (AIG), Engineering Optimization, DOI: 10.1080/0305215X.2019.1565282 

https://www.tandfonline.com/doi/abs/10.1080/0305215X.2019.1565282?journalCode=geno20

**Comment by caranha** [comment]
Thank you!
