### ISSUE TITLE
Artificial Human Optimization

### ISSUE THREAD

**Issue by albertofranzin** [fcampelo/EC-Bestiary#60]
The author consider this a new field, rather than a new algorithm. As far as I can tell, the first paper is

Gajawada, Satish. "POSTDOC: The Human Optimization." Computer Science & Information Technology (CS & IT), CSCP 3 (2013): 183-187.
pdf here: https://www.airccj.org/CSCP/vol3/csit3918.pdf

In subsequent papers this concept is expanded. The paper at
https://journals.scholarpublishing.org/index.php/TMLAI/article/view/2408
lists some of these papers - none is proposed, either a new method or a variant, still the work is given the name "Entrapreneur".

More recently, a new paper introduces some artificial human-based variants of PSO
 Novel Artificial Human Optimization Field Algorithms – The Beginning 
(https://journals.scholarpublishing.org/index.php/TMLAI/article/view/5712, pdf also at https://arxiv.org/pdf/1903.12011.pdf) with "Hybrid  PSO  algorithms  inspired by  Human  Kindness  (HKPSO),  Bipolar  Disorder  Human  Disease (HDPSO) and Human Relaxation (HRPSO)" -- also, this paper has, by far, the most epic introduction I ever found in a journal article.

**Comment by caranha** [comment]
These papers frighten me. BTW, according to google scholar the author has gone on to write the "Artificial God Optimization". I don't even want to know :worried:

**Comment by albertofranzin** [comment]
It reminds me of Dragon Ball. First, the enemies are the strongest humans. Then the strongest guys from another planet. Then the strongest one in the universe. Then the android from the future. Then the gods.

**Comment by caranha** [comment]
I'll close the issue for now. While the Artificial Human Optimization papers is extremely amusing, I don't think it counts for the bestiary because it doesn't actually propose an algorithm! :thinking: Feel free to reopen if you disagree and want to discuss this more.
