### ISSUE TITLE
New Algorithm candidates

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#70]
Jakub Grabski
Poznan University of Technology, Poland

1) Selfish herds: F. Fausto, E. Cuevas, A. Valdivia, A. Gonzalez, A global optimization algorithm inspired in the behavior of selfish herds, Biosystems, Vol. 160, 2017, pp. 39-55, DOI:  10.1016/j.biosystems.2017.07.010.
2) Emperor penguin: G. Dhiman, V. Kumar, Emperor penguin optimizer: A bio-inspired algorithm for engineering problems, Knowledge-Based Systems, Vol. 159, 2018, pp. 20-50, DOI: 10.1016/j.knosys.2018.06.001.
3) Farmland fertility: H. Shayanfar, F.S. Gharehchopogh: Farmland fertility: A new metaheuristic algorithm for solving continuous optimization problems, Applied Soft Computing, Vol. 71, 2018, pp. 728-746, DOI:  10.1016/j.asoc.2018.07.033
4) Seagull: G. Dhiman, V. Kumar: Seagull optimization algorithm: Theory and its applications for large-scale industrial engineering problems,  Knowledge-Based Systems, Vol. 165, 2019, pp. 169-196, DOI:  10.1016/j.knosys.2018.11.024
5) Yellow Saddle Goatfish behavior: D. Zaldivar, B. Morales, A. Rodriguez, A. Valdivia, E. Cuevas, M. Perez-Cisneros: A novel bio-inspired optimization model based on Yellow Saddle Goatfish behavior, Biosystems, Vol. 174, 2018, pp. 1-21, DOI: 10.1016/j.biosystems.2018.09.007
6) Lightning Attachment Procedure Optimization: A. Foroughi Nematollahi, A. Rahiminejad, B. Vahidi: A novel physical based meta-heuristic optimization method known as Lightning Attachment Procedure Optimization, Applied Soft Computing, Vol. 59, 2017, pp. 596-621, DOI: 10.1016/j.asoc.2017.06.033
7) Chaotic crow: R.M. Rizk-Allah, A. Ella Hassanien, S. Bharracharyya, Chaotic crow search algorithm for fractional optimization problems, Applied Soft Computing, Vol. 71, 2018, pp. 1161-1175, DOI:  10.1016/j.asoc.2018.03.019

**Comment by fcampelo** [comment]
Buzzards! http://mjee.iaumajlesi.ac.ir/index/index.php/ee/article/view/3363

**Comment by caranha** [comment]
Selfish herds: Already Added.
Emperor Penguin: Already Added.
Farmland Fertility: Added.
Seagull: Already Added.
Yellow Saddle Goldfish: Already Added.
Lighting Attachemnt: Repeated Heuristic (Lighting search, 2015)
Chaotic Crows: Added
