### ISSUE TITLE
Paper suggestions

### ISSUE THREAD

**Issue by sjvrijn** [fcampelo/EC-Bestiary#72]
Here's a list of possible suggestions. There's a few about which I'm not entirely sure whether you'd want them on the list. Can you give a yes/no on each of these?

- **Artificial Physics Optimization**: Gorbenko, A., and Popov, V. (2012) The force law design of artificial physics optimization for robot anticipation of motion. Advanced Studies in Theoretical Physics, 6, 625-628. (no doi)
- **Gravitational Interactions Optimization**: Flores, J. J., López, R., and Barrera, J. (2011) Gravitational interactions optimization. International Conference on Learning and Intelligent Optimization, pp. 226-237, 17-21 January, Springer, Rome. https://doi.org/10.1007/978-3-642-25566-3_17
- **Curved Space Optimization**: Moghaddam, F. F., Moghaddam, R. F., and Cheriet, M. (2012) Curved space optimization: a random search based on general relativity theory. arXiv preprint arXiv:1208.2214. (no doi)
- **Artificial Bee Colony** (a seemingly different one? not entirely sure...): Basturk, B., Karaboga, D.: An Artificial Bee Colony (ABC) Algorithm for Numeric function Optimization. In: IEEE Swarm Intelligence Symposium 2006, Indianapolis, Indiana, USA, May 12-14 (2006) (no doi)
- **Deer Hunting Optimization Algorithm**: Brammya, G., Praveena, S., Ninu Preetha, N., Ramya, R., Rajakumar, B., and Binu, D. (2019) Deer Hunting Optimization Algorithm: A New Nature-Inspired Meta-heuristic Paradigm. The Computer Journal, bxy133. doi: https://doi.org/10.1093/comjnl/bxy133
- **Virus Optimization Algorithm** (yet another one): Liang, Y.-C., and Cuevas Juarez, J. R. (2016) A novel metaheuristic for continuous optimization problems: Virus optimization algorithm. Engineering Optimization, 48, 73-93. https://doi.org/10.1080/0305215X.2014.994868
- **Soccer League Competition Algorithm**: N. Moosavian and B. Roodsari, "Soccer League Competition Algorithm, a New Method for Solving Systems of Nonlinear Equations," International Journal of Intelligence Science, Vol. 4 No. 1, 2014, pp. 7-16. doi: 10.4236/ijis.2014.41002.
- **Sine Cosine Algorithm**: Mirjalili, S. (2016). SCA: a sine cosine algorithm for solving optimization problems. Knowledge-Based Systems, 96, 120-133. https://doi.org/10.1016/j.knosys.2015.12.022

**Comment by caranha** [comment]
Hello Sander, thank you for your suggestions!

- Artificial Physics: Not a metaphor, the paper optimizes the physics of a simulated swarm of robots.
- Gravitation Interation: A bit overlapping with Gravitational, but added!
- Curved Space: Only arxiv link, does not look like it was actually published anywhere. Skip for now
- ABC: Yeah, the ABC that everyone cites is Karaboga 2007, I didn't know about this 2006 paper (and I can't find it online...) the 2006 paper we cite is a completely different algorithm (BCO). I have no idea how similar or different they are. Metaphors are a mess, aren't they?
- Deer Hunting: Added under Humans!
- Virus: Added, we have quite a big collection now
- Soccer League: Added
- Sine Cosine: Not really a metaphor, skipped.
