### ISSUE TITLE
Mimics the person’s life

### ISSUE THREAD

**Issue by ciniro** [fcampelo/EC-Bestiary#78]
Future search algorithm for optimization
Evolutionary Intelligence, Volume 12, pages21–31(2019)

https://link.springer.com/article/10.1007/s12065-018-0172-2

"(...) his algorithm mimics the person’s life. People in the world search for the best life. If any person found that his life is not good, he tries to change it and he imitates the successful persons." 💯 

@Article{Elsisi2018,
  author    = {M. Elsisi},
  journal   = {Evolutionary Intelligence},
  title     = {Future search algorithm for optimization},
  year      = {2018},
  month     = {sep},
  number    = {1},
  pages     = {21--31},
  volume    = {12},
  doi       = {10.1007/s12065-018-0172-2},
  publisher = {Springer Science and Business Media {LLC}},
}

**Comment by caranha** [comment]
Lol, do you believe that there is ALREADY an algorithm based on "Life Choices"? :-P
