### ISSUE TITLE
Add heuristic spotted by Kenneth Sörensen

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#9]
The Golden Ball Algorithm: http://dl.acm.org/citation.cfm?id=2636011

Gotta check what exact metaphor that is...

**Comment by caranha** [comment]
A very quick read shows that this is a variation on Island models where the population is divided in "soccer teams" (sub-populations) and their fitness is compared in "tournaments". After the tournaments, the "players" (candidate solutions) are "transferred" according to the results of the sub-populations.

There is a LOT of soccer lingo in the paper.

**Comment by caranha** [comment]
Paper details from the acm page:

E. Osaba, F. Diaz, E. Onieva
Journal Applied Intelligence archive, Volume 41 Issue 1, July 2014, Pages 145-166

**Comment by caranha** [comment]
So, we already have a soccer meta-heuristic (under *S*), not sure if this counts as a different one. Will think about it later :-P

**Comment by fcampelo** [comment]
I agree. If there are enough differences we may opt by turning "Soccer" into a subcategory and listing the papers under it. "Golden Ball" is a juicy title ;-)

**Comment by caranha** [comment]
hmm, I'm reluctant to dwell too deep into subcategories, for the pure
reason of laziness. The number of bee variations alone would be staggering
:)

**Comment by fcampelo** [comment]
Indeed.
