### ISSUE TITLE
Kestrel-based search algorithm (KSA)

### ISSUE THREAD

**Issue by nguyentrihai93** [fcampelo/EC-Bestiary#91]
List of related publications:
- Kestrel-Based Search Algorithm (KSA) for Parameter Tuning Unto Long Short Term Memory (LSTM) Network for Feature Selection in Classification of High-Dimensional Bioinformatics Datasets
- Bioinspired Computational Approach to Missing Value Estimation
- Kestrel-Based Search Algorithm for Association Rule Mining and Classification of Frequently Changed Items
- Integration of Kestrel-based search algorithm with artificial neural network for feature subset selection
- Bio-inspired energy efficient clustering approach for wireless sensor networks

**Comment by caranha** [comment]
Thank you! I have added the oldest of those papers.
